[package]
name = "Quilty-Rustodon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
json = "0.12.4"
reqwest = "0.11.14"
tui = "0.19.0"
url = "2.3.1"

